import PlatformExpertise from "./PlatformExpertise";

const services = [
  ["☁", "Cloud Strategy & Migration", "Plan, migrate and optimise for the cloud."],
  ["◇", "Cybersecurity & Risk", "Protect what matters. Build resilience."],
  ["▤", "Data & AI Solutions", "Turn data into opportunity."],
  ["⌘", "Digital Transformation", "Modernise. Innovate. Grow."],
  ["⚙", "Managed Services", "Reliable technology. Real impact."],
  ["◎", "Advisory & Enablement", "Strategy, skills and support for lasting change."],
];
const industries = ["Financial Services", "Public Sector", "Telecommunications", "Energy & Resources", "Healthcare", "Retail & Consumer", "Manufacturing", "Education"];

function Logo(){return <a className="brand" href="#top" aria-label="African Footprint Technologies home"><span className="logoMark" aria-hidden="true"><svg viewBox="0 0 92 92"><path className="fp f1" d="M48 7C26 7 10 23 10 43c0 12 5 22 13 30"/><path className="fp f2" d="M48 15c-17 0-30 12-30 28 0 13 7 23 18 29"/><path className="fp f3" d="M49 23c-12 0-22 8-22 20 0 11 8 18 17 22"/><path className="fp f4" d="M49 31c-8 0-14 5-14 12 0 8 7 12 13 15"/><path className="fp goldLine" d="M55 9c12 2 22 9 27 18M63 18c8 3 14 8 18 14"/><path className="africaShape" d="M43 24l10-4 10 5 6 8-4 8 3 9-8 8-3 12-7 13-5-10-7-7 2-11-7-8 5-8-2-8z"/><path className="cloudShape" d="M55 50h24c6 0 10-4 10-9s-4-9-9-9c-1-8-7-13-15-13-7 0-13 4-15 11-6 0-11 4-11 10 0 6 5 10 11 10z"/></svg></span><span className="brandText"><b>African<br/>Footprint</b><span>Technologies</span><small>CLOUDING A BRIGHTER AFRICA</small></span></a>}

export default function Home(){return <main id="top">
<header className="nav shell"><Logo/><nav aria-label="Main navigation"><a className="active" href="#top">Home</a><a href="#about">About</a><a href="#services">Services</a><a href="#industries">Industries</a><a href="#insights">Insights</a><a href="#contact">Contact</a></nav><a className="pill dark" href="#contact">Let&apos;s Talk <span>→</span></a></header>
<section className="hero"><div className="heroShade"/><div className="shell heroInner"><div className="heroCopy"><p className="eyebrow">PEOPLE. TECHNOLOGY. OPPORTUNITY. ACROSS AFRICA.</p><h1>Building Africa&apos;s<br/>Digital Tomorrow.</h1><h2>Cloud. Technology. Transformation. Across Africa.</h2><p>We help organisations build, secure and scale their technology footprint across Africa — harnessing the power of cloud and innovative technologies to create a more connected, inclusive and prosperous continent.</p><div className="actions"><a className="pill green" href="#services">Explore Our Services →</a><a className="pill outline" href="#about">About Us</a></div></div><div className="heroMeta"><div className="script">Same Continent.<br/><b>Greater Possibilities.</b></div><div className="networkDots" aria-hidden="true"><i/><i/><i/><i/><i/><i/></div><div className="location">● &nbsp; CAPE TOWN, SOUTH AFRICA<br/><small>OUR HOME. A BRIGHTER AFRICA.</small></div></div></div></section>
<section className="services shell" id="services">{services.map(([icon,title,desc])=><article key={title}><div className="serviceIcon">{icon}</div><h3>{title}</h3><p>{desc}</p></article>)}</section>
<PlatformExpertise/>
<section className="purpose" id="about"><div className="shell purposeGrid"><div><p className="eyebrow mint">OUR PURPOSE</p><h2>A more connected,<br/>inclusive and prosperous<br/>Africa is <em>within reach.</em></h2><p>African Footprint Technologies is a technology consulting and solutions partner, enabling businesses and governments to unlock Africa&apos;s potential through cloud, data, security and digital innovation.</p><a className="pill green" href="#contact">Our Story →</a></div><div className="africaMap" aria-label="Abstract connected Africa graphic"><span>AFRICA</span>{[1,2,3,4,5,6,7,8,9,10,11].map(n=><i key={n}/>)}</div><aside><strong>54</strong><span>AFRICAN COUNTRIES</span><strong>1</strong><span>BOLDER TOMORROW</span><strong>∞</strong><span>OPPORTUNITIES</span><hr/><p>TECHNOLOGY<br/>THAT LEAVES A<br/>POSITIVE FOOTPRINT.</p></aside></div></section>
<section className="industry shell" id="industries"><div className="sectionIntro"><div><p className="eyebrow">INDUSTRIES WE SERVE</p><h2>Real Solutions for<br/>Real African Impact.</h2></div><div><p>We work with forward-thinking organisations across the continent to solve complex challenges and create lasting value.</p><a href="#contact">Explore Industries →</a></div></div><div className="industryRow">{industries.map((x,i)=><div key={x}><b>{["▰","▥","⌁","◈","✚","▽","▥","◇"][i]}</b><span>{x}</span></div>)}</div></section>
<section className="insights" id="insights"><div className="shell insightGrid"><div className="quote"><span>Technology<br/>for a stronger,<br/>more inclusive<br/>Africa.</span><small>CLOUDING A BRIGHTER AFRICA</small></div><div><p className="eyebrow mint">INSIGHTS</p><h2>Ideas. Perspectives.<br/>Progress.</h2><p>Explore our thinking on cloud, technology and Africa&apos;s digital future.</p><a className="pill gold" href="#contact">View Insights →</a></div><article className="article"><div className="articleVisual">AFT</div><h3>From Cloud to Opportunity: Accelerating Africa&apos;s Digital Future</h3><small>INSIGHTS · AFRICAN FOOTPRINT TECHNOLOGIES</small></article></div></section>
<section className="cta shell"><p className="eyebrow">READY TO BUILD WHAT&apos;S NEXT?</p><h2>Let&apos;s create a stronger digital footprint across Africa.</h2><a className="pill green" href="mailto:hello@africanfootprint.tech">Start a conversation →</a></section>
<footer id="contact"><div className="shell footerGrid"><Logo/><div><b>Quick Links</b><a href="#about">About</a><a href="#services">Services</a><a href="#platforms">Platforms</a><a href="#industries">Industries</a></div><div><b>Platform Focus</b><span>Salesforce · Zoho CRM</span><span>ServiceNow · NetSuite</span><span>DocuSign · SignNow</span><span>AWS</span></div><div><b>Contact</b><span>Cape Town, South Africa</span><a href="mailto:hello@africanfootprint.tech">hello@africanfootprint.tech</a><small>Contact details are placeholders until confirmed.</small></div></div><div className="shell legal">© 2026 African Footprint Technologies <span>Same Continent. Greater Possibilities.</span></div></footer>
</main>}
