import PlatformExpertise from "./PlatformExpertise";

const services = [
  ["☁", "Cloud & AWS", "Architecture, migration, optimisation and cloud operations."],
  ["◇", "CRM & Customer Experience", "Salesforce and Zoho CRM consulting that connects teams and customers."],
  ["▤", "Enterprise Platforms", "ServiceNow and NetSuite implementation, integration and optimisation."],
  ["⌘", "Digital Agreements", "DocuSign and SignNow workflows that simplify how business gets done."],
  ["⚙", "Integration & Automation", "Connect platforms, data and processes across the enterprise."],
  ["◎", "Advisory & Managed Support", "Strategy, enablement and ongoing support for lasting value."],
];
const industries = ["Financial Services", "Public Sector", "Telecommunications", "Energy & Resources", "Healthcare", "Retail & Consumer", "Manufacturing", "Education"];
function Logo(){return <a className="brand" href="#top" aria-label="African Footprint Technologies home"><span className="brandMark" aria-hidden="true"><span className="africa">◒</span><span className="cloud">☁</span></span><span className="brandText"><b>African<br/>Footprint</b><span>Technologies</span><small>CLOUDING A BRIGHTER AFRICA</small></span></a>}
export default function Home(){return <main id="top">
<header className="nav shell"><Logo/><nav aria-label="Main navigation"><a href="#top">Home</a><a href="#about">About</a><a href="#services">Services</a><a href="#platforms">Platforms</a><a href="#industries">Industries</a><a href="#contact">Contact</a></nav><a className="pill dark" href="#contact">Let&apos;s Talk <span>→</span></a></header>
<section className="hero"><div className="heroGlow one"/><div className="heroGlow two"/><div className="shell heroInner"><div className="heroCopy"><p className="eyebrow">PEOPLE. TECHNOLOGY. OPPORTUNITY. ACROSS AFRICA.</p><h1>Building Africa&apos;s<br/>Digital <em>Tomorrow.</em></h1><h2>Cloud. Enterprise Platforms. Transformation. Across Africa.</h2><p>We help organisations select, implement, integrate and optimise the technology platforms that run modern business — bringing global cloud capability together with an African footprint.</p><div className="actions"><a className="pill green" href="#platforms">Explore Our Platforms →</a><a className="pill outline" href="#about">About Us</a></div></div><div className="heroArt" aria-label="Stylised African digital network"><div className="sun"/><div className="mountain m1"/><div className="mountain m2"/><div className="network"><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="script">Same Continent.<br/><b>Greater Possibilities.</b></div><div className="location">◆ CAPE TOWN, SOUTH AFRICA<br/><small>OUR HOME. A BRIGHTER AFRICA.</small></div></div></div></section>
<section className="services shell" id="services">{services.map(([icon,title,desc])=><article key={title}><div className="serviceIcon">{icon}</div><h3>{title}</h3><p>{desc}</p></article>)}</section>
<PlatformExpertise/>
<section className="purpose" id="about"><div className="shell purposeGrid"><div><p className="eyebrow mint">OUR PURPOSE</p><h2>Global technology.<br/>Local understanding.<br/><em>Lasting impact.</em></h2><p>African Footprint Technologies is a technology consulting and solutions partner helping organisations across Africa get more value from cloud, CRM, enterprise service management, ERP, digital agreement and automation platforms.</p><a className="pill green" href="#contact">Our Story →</a></div><div className="africaMap" aria-label="Abstract connected Africa graphic"><span>AFRICA</span>{[1,2,3,4,5,6,7,8,9,10,11].map(n=><i key={n}/>)}</div><aside><strong>7</strong><span>PRIMARY PLATFORMS</span><strong>1</strong><span>AFRICAN FOCUS</span><strong>∞</strong><span>OPPORTUNITIES</span><hr/><p>TECHNOLOGY<br/>THAT LEAVES A<br/>POSITIVE FOOTPRINT.</p></aside></div></section>
<section className="industry shell" id="industries"><div className="sectionIntro"><div><p className="eyebrow">INDUSTRIES WE SERVE</p><h2>Real Solutions for<br/>Real African Impact.</h2></div><div><p>We work with forward-thinking organisations across the continent to solve complex challenges and create lasting value.</p><a href="#contact">Explore Industries →</a></div></div><div className="industryRow">{industries.map((x,i)=><div key={x}><b>{["▰","▥","⌁","◈","✚","▽","▥","◇"][i]}</b><span>{x}</span></div>)}</div></section>
<section className="insights" id="insights"><div className="shell insightGrid"><div className="quote"><span>Technology<br/>for a stronger,<br/>more inclusive<br/>Africa.</span><small>CLOUDING A BRIGHTER AFRICA</small></div><div><p className="eyebrow mint">OUR APPROACH</p><h2>Advise. Implement.<br/>Enable. Support.</h2><p>From platform strategy and solution design to implementation, integration and managed support, we stay focused on business outcomes and knowledge transfer.</p><a className="pill gold" href="#contact">Talk to a Consultant →</a></div><article className="article"><div className="articleVisual">AFT</div><h3>Global technology platforms. Consulting built for African organisations.</h3><small>AFRICAN FOOTPRINT TECHNOLOGIES</small></article></div></section>
<section className="cta shell"><p className="eyebrow">READY TO GET MORE FROM YOUR TECHNOLOGY?</p><h2>Let&apos;s build a technology footprint designed for your organisation and your market.</h2><a className="pill green" href="mailto:hello@africanfootprint.tech">Start a conversation →</a></section>
<footer id="contact"><div className="shell footerGrid"><Logo/><div><b>Quick Links</b><a href="#about">About</a><a href="#services">Services</a><a href="#platforms">Platforms</a><a href="#industries">Industries</a></div><div><b>Platform Focus</b><span>Salesforce · Zoho CRM</span><span>ServiceNow · NetSuite</span><span>DocuSign · SignNow</span><span>AWS</span></div><div><b>Contact</b><span>Cape Town, South Africa</span><a href="mailto:hello@africanfootprint.tech">hello@africanfootprint.tech</a><small>Contact details are placeholders until confirmed.</small></div></div><div className="shell legal">© 2026 African Footprint Technologies (Pty) Ltd. <span>Same Continent. Greater Possibilities.</span></div></footer>
</main>}
