import Link from "next/link";import {notFound} from "next/navigation";import {SiteFooter,SiteHeader} from "../../components/SiteChrome";
const data:{[key:string]:{name:string,kicker:string,intro:string,capabilities:string[],outcomes:string[]}}={
'salesforce':{name:'Salesforce',kicker:'CRM & CUSTOMER EXPERIENCE',intro:'Design and evolve Salesforce environments around the way your teams sell, serve and engage customers.',capabilities:['CRM strategy & roadmap','Solution design & implementation','Data migration & integration','Automation & workflow design','Adoption, enablement & optimisation','Managed platform support'],outcomes:['Connected customer journeys','Better pipeline and service visibility','Higher user adoption']},
'zoho-crm':{name:'Zoho CRM',kicker:'CRM & BUSINESS OPERATIONS',intro:'Build practical, connected CRM experiences with Zoho CRM for growing and established African organisations.',capabilities:['CRM design & configuration','Sales process automation','Data migration','Integration with business systems','Reporting & dashboards','Ongoing optimisation'],outcomes:['Simpler sales operations','Better customer visibility','Scalable CRM foundations']},
'servicenow':{name:'ServiceNow',kicker:'ENTERPRISE SERVICE MANAGEMENT',intro:'Transform service delivery with workflows that connect people, processes and enterprise operations.',capabilities:['Service management strategy','Workflow & catalogue design','Implementation & configuration','Integration & automation','Governance & optimisation','Managed support'],outcomes:['More consistent service delivery','Reduced manual workflows','Improved operational visibility']},
'signnow':{name:'SignNow',kicker:'DIGITAL SIGNATURE WORKFLOWS',intro:'Digitise signature and document workflows to make approvals faster, clearer and easier to manage.',capabilities:['Workflow discovery','Template & signing design','Implementation','Integration','Process automation','User enablement'],outcomes:['Faster turnaround','Less manual administration','More consistent document processes']},
'docusign':{name:'DocuSign',kicker:'DIGITAL AGREEMENTS',intro:'Modernise agreement processes with DocuSign implementation, integration and workflow consulting.',capabilities:['Agreement workflow design','eSignature implementation','Template strategy','System integration','Automation','Adoption & optimisation'],outcomes:['Faster agreements','Improved process visibility','Reduced administrative friction']},
'netsuite':{name:'NetSuite',kicker:'CLOUD ERP & BUSINESS SYSTEMS',intro:'Connect finance and operations with NetSuite solutions designed around business processes and growth.',capabilities:['ERP strategy & discovery','Solution design','Implementation support','Data migration','Integration','Optimisation & reporting'],outcomes:['Connected operations','Stronger financial visibility','Scalable business processes']},
'aws':{name:'AWS',kicker:'CLOUD INFRASTRUCTURE & SERVICES',intro:'Plan, migrate and optimise workloads on AWS with security, resilience, cost and operational capability in view.',capabilities:['Cloud strategy & assessment','Architecture & landing zones','Migration planning & delivery','Security & governance','Cost optimisation','Cloud operations & enablement'],outcomes:['Secure cloud foundations','More resilient workloads','Clearer cloud operating model']}}
export function generateStaticParams(){return Object.keys(data).map(slug=>({slug}))}
export default async function Platform({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=data[slug];if(!p)notFound();return <><SiteHeader/><main><section className="platformHero"><div className="shell"><p className="eyebrow">{p.kicker}</p><h1>{p.name} consulting.<br/><em>Built around outcomes.</em></h1><p>{p.intro}</p><Link className="pill green" href="/contact">Discuss your {p.name} roadmap →</Link></div></section><section className="innerSection shell split"><div><p className="eyebrow">HOW WE HELP</p><h2>From roadmap to optimisation.</h2></div><div className="capList">{p.capabilities.map((x,i)=><div key={x}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span></div>)}</div></section><section className="darkBand"><div className="shell"><p className="eyebrow mint">BUSINESS OUTCOMES</p><div className="outcomeGrid">{p.outcomes.map(x=><h3 key={x}>{x}</h3>)}</div></div></section><section className="innerSection shell"><p className="eyebrow">AFT DELIVERY MODEL</p><h2 className="wideHeading">Advise. Implement. Integrate. Enable. Support.</h2><p className="leadCopy">We shape the engagement around your current environment, priorities and internal capability — from a focused advisory assignment to implementation and ongoing managed support.</p><Link className="pill dark" href="/services">Explore all services →</Link></section></main><SiteFooter/></>}
